/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.github.subjekt.kotlin-library-conventions")
    antlr
    kotlin("jvm")
}

sourceSets {
  main {
    java {
      // telling that output generateGrammarSource should be part of main source set
      // actuall passed value will be equal to `outputDirectory` that we configured above
      srcDir(tasks.generateGrammarSource)
    }
  }
}

dependencies {
  // https://mvnrepository.com/artifact/org.antlr/antlr4
  implementation("org.antlr:antlr4:4.13.2")
  // https://mvnrepository.com/artifact/org.antlr/antlr4-runtime
  implementation("org.antlr:antlr4-runtime:4.13.2")

}

tasks.generateGrammarSource {
  // set output directory to some arbitrary location in `/build` directory.
  // by convention `/build/generated/sources/main/java/<generator name>` is often used
  outputDirectory = file("${layout.buildDirectory}/generated/sources/main/java/antlr")

  // pass -package to make generator put code in not default space
}
