/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.subjekt.app

import io.github.subjekt.cli.EntryPointCommand
import picocli.CommandLine

fun main(args: Array<String>) {
  val cmd = CommandLine(EntryPointCommand())
  try {
    cmd.execute(*args)
  } catch (ex: Exception) {
    println("Error: ${ex.message}")
  }
}
