/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  id("io.github.subjekt.kotlin-application-conventions")
  alias(libs.plugins.shadowJar)
}

dependencies {
  implementation(project(":generator"))
  implementation(libs.picocli)
}

application {
  // Define the main class for the application.
  mainClass.set("io.github.subjekt.app.AppKt")
}
