/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.github.subjekt.kotlin-application-conventions")
}

dependencies {
    implementation(project(":generator"))
}

application {
    // Define the main class for the application.
    mainClass.set("io.github.subjekt.app.AppKt")
}
